% -------------------------------------------------------------------
%  Generated by MATLAB on 14-Nov-2025 10:30:14
%  MATLAB version: 25.2.0.3042426 (R2025b) Update 1
% -------------------------------------------------------------------
                                       

Sig = Simulink.Signal;
Sig.CoderInfo.StorageClass = 'Auto';
Sig.Description = '';
Sig.DataType = 'auto';
Sig.Min = [];
Sig.Max = [];
Sig.DocUnits = '';
Sig.Dimensions = -1;
Sig.DimensionsMode = 'auto';
Sig.Complexity = 'auto';
Sig.SampleTime = -1;
Sig.InitialValue = '';

link_id = 1;

main_switch = Simulink.Parameter;
main_switch.Value = true;
main_switch.HasCoderInfo = false;
main_switch.Description = '';
main_switch.DataType = 'boolean';
main_switch.Min = [];
main_switch.Max = [];
main_switch.DocUnits = '';

motor_e_stop = Simulink.Parameter;
motor_e_stop.Value = false;
motor_e_stop.HasCoderInfo = false;
motor_e_stop.Description = '';
motor_e_stop.DataType = 'boolean';
motor_e_stop.Min = [];
motor_e_stop.Max = [];
motor_e_stop.DocUnits = '';

quick_stop = Simulink.Parameter;
quick_stop.Value = false;
quick_stop.HasCoderInfo = false;
quick_stop.Description = '';
quick_stop.DataType = 'boolean';
quick_stop.Min = [];
quick_stop.Max = [];
quick_stop.DocUnits = '';

useGenerator = Simulink.Parameter;
useGenerator.Value = false;
useGenerator.HasCoderInfo = false;
useGenerator.Description = '';
useGenerator.DataType = 'boolean';
useGenerator.Min = [];
useGenerator.Max = [];
useGenerator.DocUnits = '';

